export default {
    BLACK: '#000',
    DARK_BLUE: '#2924A6',
    GOLD: '#FCDB9C',
    GREEN: '#B9FAB3',
    GREY_BLUE: '#E2E5F4',
    LIGHT_BLUE: '#F5F6FB',
    LIGHT_GREEN: '#C9F6F4',
    LIGHTER_WHITE: '#F3F3F3',
    ORANGE: '#FFD9DD',
    PINK: '#EFCDFF',
    SKY_BLUE: '#8EFFFA',
    WHITE: '#fff',
    YELLOW: '#FEFFBB',
};